"""
api/setup.py — the first-run setup wizard's backend (Phase C).

Local-first trust model: this runs on localhost for the machine's owner, so
writing ~/.tickerlens/config.toml and .env from the wizard is appropriate —
secrets never leave the machine and never enter the repo. After save, config
live-reloads (config.reload()) so no restart is needed.
"""
from __future__ import annotations

import os
import stat

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

import config
from providers import registry
from providers.base import SUBSCRIPTIONS

router = APIRouter(prefix="/api/setup")


def _keys(provider: str) -> list[str]:
    """Env-var names a provider needs — derived from providers.base.SUBSCRIPTIONS
    (the single source of truth) so this file never hardcodes key names."""
    return [env for _name, env in SUBSCRIPTIONS.get(provider, {}).get("secrets", [])]


# What each bundled provider needs from the user (the wizard renders this).
# Labels/notes are wizard copy; the key lists come from SUBSCRIPTIONS.
PROVIDER_INFO = {
    "schwab": {"label": "Charles Schwab (broker — quotes/history/options/account)",
               "keys": _keys("schwab"),
               "note": ("Create an app at developer.schwab.com. First OAuth "
                        "must run once in a terminal (schwab-py mints "
                        "~/.tickerlens/schwab_token.json; re-auth ~weekly).")},
    "finnhub": {"label": "Finnhub (free key — fundamentals/news/analyst/earnings)",
                "keys": _keys("finnhub"),
                "note": "Free key at finnhub.io/register."},
    "yfinance": {"label": "yfinance (no key — unofficial price data)",
                 "keys": _keys("yfinance"), "note": "bundled — works with zero setup"},
    "stocktwits": {"label": "StockTwits (no key — social sentiment)",
                   "keys": _keys("stocktwits"), "note": ""},
    "edgar": {"label": "SEC EDGAR (no key — insider filings)", "keys": _keys("edgar"),
              "note": "Requires your contact email (SEC fair-use policy)."},
    "finra": {"label": "FINRA (no key — short interest)", "keys": _keys("finra"), "note": ""},
    "none": {"label": "None — disable this capability", "keys": [], "note": ""},
}


@router.get("/status")
def status():
    cfg_exists = os.path.exists(os.path.join(config.TICKERLENS_HOME, "config.toml"))
    return {
        "configured": cfg_exists and config.USER_NAME != "the user",
        "home": config.TICKERLENS_HOME,
        "user_name": config.USER_NAME if config.USER_NAME != "the user" else None,
        "contact_email": config.CONTACT_EMAIL,
    }


@router.get("/options")
def options():
    """Per capability: which bundled providers implement it (+ key needs)."""
    caps = {}
    for cap in config.CAPABILITY_DEFAULTS:
        impl = sorted(registry.IMPLEMENTATIONS.get(cap, {}).keys() - {"mock"})
        caps[cap] = {"providers": impl + ["none"],
                     "current": config.CAPABILITIES_CONFIG.get(cap, "none")}
    return {"capabilities": caps, "provider_info": PROVIDER_INFO}


class SaveBody(BaseModel):
    name: str
    contact_email: str
    capabilities: dict[str, str]
    secrets: dict[str, str] = {}


@router.post("/save")
def save(body: SaveBody):
    if not body.name.strip():
        raise HTTPException(422, "name is required")
    if "@" not in body.contact_email:
        raise HTTPException(422, "a real contact email is required (SEC EDGAR policy)")
    for cap, prov in body.capabilities.items():
        if cap not in config.CAPABILITY_DEFAULTS:
            raise HTTPException(422, f"unknown capability: {cap}")
        if prov != "none" and prov not in registry.IMPLEMENTATIONS.get(cap, {}):
            raise HTTPException(422, f"{prov} does not implement {cap}")

    os.makedirs(config.TICKERLENS_HOME, exist_ok=True)
    lines = ["# TickerLens instance config — generated by the setup wizard", "",
             "[user]", f'name = "{body.name.strip()}"',
             f'contact_email = "{body.contact_email.strip()}"', "",
             "[capabilities]"]
    for cap in config.CAPABILITY_DEFAULTS:
        lines.append(f'{cap} = "{body.capabilities.get(cap, config.CAPABILITY_DEFAULTS[cap])}"')
    with open(os.path.join(config.TICKERLENS_HOME, "config.toml"), "w") as f:
        f.write("\n".join(lines) + "\n")

    if body.secrets:
        env_path = os.path.join(config.TICKERLENS_HOME, ".env")
        existing: dict[str, str] = {}
        if os.path.exists(env_path):
            for line in open(env_path):
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    existing[k.strip()] = v.strip()
        for k, v in body.secrets.items():
            if v.strip():
                existing[k.strip()] = v.strip()
        with open(env_path, "w") as f:
            f.write("\n".join(f"{k}={v}" for k, v in existing.items()) + "\n")
        os.chmod(env_path, stat.S_IRUSR | stat.S_IWUSR)  # 600 — owner only

    config.reload()
    return {"ok": True, "home": config.TICKERLENS_HOME}


@router.post("/test/{provider}")
def test_provider(provider: str):
    module = registry.MODULES.get(provider)
    if module is None:
        raise HTTPException(404, "unknown provider")
    try:
        return {"provider": provider, "ok": bool(module.health_check())}
    except Exception as e:
        return {"provider": provider, "ok": False, "detail": str(e)[:200]}
